"""empty message

Revision ID: ceb48e6bb5fe
Revises: 127b3c815962
Create Date: 2019-02-19 15:00:27.207511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb48e6bb5fe'
down_revision = '127b3c815962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('profile_pic', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
